<a href="https://colab.research.google.com/github/dmutua618-wq/OUK-Data-Science/blob/main/My_First_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [5]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [4]:
import pandas as pd
print("Google Colab is ready!")

# Create a quick table
df = pd.DataFrame({'Name': ['Eric', 'Alex'], 'Status': ['Online', 'Coding']})
df

Google Colab is ready!

   Name  Status
0  Eric  Online
1  Alex  Coding

In [7]:
# Convert Vol to numeric, turning errors (like text) into NaN (nulls)
df["Vol"] = pd.to_numeric(df["Vol"], errors="coerce")

# Now check how many nulls were created
print(f"Missing values in Vol: {df['Vol'].isnull().sum()}")

KeyError: 'Vol'

In [8]:
path = "PASTE_YOUR_PATH_HERE"
df = pd.read_csv(path)

FileNotFoundError: [Errno 2] No such file or directory: 'PASTE_YOUR_PATH_HERE'

In [10]:
import pandas as pd
import io

# This creates a sample version of the oil_prices.csv file mentioned in your notes
csv_content = """date,year,month,day,Price,Vol
2021-12-01,2021,12,1,70.12,450K
2021-12-02,2021,12,2,69.50,420K
2021-12-03,2021,12,3,71.20,
2021-12-04,2021,12,4,72.10,380K
2021-01-01,2021,01,1,54.77,310K
2020-05-10,2020,05,10,29.38,200K
2019-11-15,2019,11,15,63.21,
2022-03-14,2022,03,14,117.25,600K
2021-12-25,2021,12,25,74.17,350K
2021-12-31,2021,12,31,75.10,
"""

# Save this to a file named oil_prices.csv
with open('oil_prices.csv', 'w') as f:
    f.write(csv_content)

print("File 'oil_prices.csv' has been created successfully!")

File 'oil_prices.csv' has been created successfully!

In [17]:
# 1. Load the data
path = "oil_prices.csv"
df = pd.read_csv(path)

# 2. Convert columns to correct types (as per your notes)
df["Vol"] = pd.to_numeric(df["Vol"].str.replace('K', ''), errors="coerce")
df['day'] = df['day'].astype('category')
df['month'] = df['month'].astype('category')
df['year'] = df['year'].astype('category')

# 3. View the data
print("--- Top 5 Rows ---")
print(df.head(5))

# 4. Filter: December 2021
print("\n--- December 2021 Records ---")
dec_2021 = df.loc[(df.year == 2021) & (df.month == 12), :]
print(dec_2021)

# 5. Descriptive Statistics
print("\n--- Statistics for Numeric Columns ---")
print(df.describe())

print("\n--- Statistics for Categorical Columns ---")
print(df.describe(include=['category']))

# 6. Count missing values in Vol
missing_vol = df['Vol'].isnull().sum()
print(f"\nNumber of missing records in Vol: {missing_vol}")

--- Top 5 Rows ---
         date  year month day  Price    Vol
0  2021-12-01  2021    12   1  70.12  450.0
1  2021-12-02  2021    12   2  69.50  420.0
2  2021-12-03  2021    12   3  71.20    NaN
3  2021-12-04  2021    12   4  72.10  380.0
4  2021-01-01  2021     1   1  54.77  310.0

--- December 2021 Records ---
         date  year month day  Price    Vol
0  2021-12-01  2021    12   1  70.12  450.0
1  2021-12-02  2021    12   2  69.50  420.0
2  2021-12-03  2021    12   3  71.20    NaN
3  2021-12-04  2021    12   4  72.10  380.0
8  2021-12-25  2021    12  25  74.17  350.0
9  2021-12-31  2021    12  31  75.10    NaN

--- Statistics for Numeric Columns ---
            Price         Vol
count   10.000000    7.000000
mean    69.680000  387.142857
std     21.625842  124.326758
min     29.380000  200.000000
25%     64.782500  330.000000
50%     70.660000  380.000000
75%     73.652500  435.000000
max    117.250000  600.000000

--- Statistics for Categorical Columns ---
        year  month  day
count     10     10   10
unique     4      5    9
top     2021     12    1
freq       7      6    2

Number of missing records in Vol: 3

In [19]:
# The colon : means "all rows"
# The list ["year", "Price"] specifies the columns
filtered_cols = df.loc[:, ["year", "Price"]]
filtered_cols.head()

   year  Price
0  2021  70.12
1  2021  69.50
2  2021  71.20
3  2021  72.10
4  2021  54.77

In [21]:
df.loc[0:4, :]

         date  year month day  Price    Vol
0  2021-12-01  2021    12   1  70.12  450.0
1  2021-12-02  2021    12   2  69.50  420.0
2  2021-12-03  2021    12   3  71.20    NaN
3  2021-12-04  2021    12   4  72.10  380.0
4  2021-01-01  2021     1   1  54.77  310.0

In [23]:
#filtering by condition
df.loc[df['Price'] > 70, :]

         date  year month day   Price    Vol
0  2021-12-01  2021    12   1   70.12  450.0
2  2021-12-03  2021    12   3   71.20    NaN
3  2021-12-04  2021    12   4   72.10  380.0
7  2022-03-14  2022     3  14  117.25  600.0
8  2021-12-25  2021    12  25   74.17  350.0
9  2021-12-31  2021    12  31   75.10    NaN

In [25]:
#null entries or not a number
df.loc[df['Price'].isnull(), :]

Empty DataFrame
Columns: [date, year, month, day, Price, Vol]
Index: []

In [28]:
#null entries or not a number
df.loc[df.isnull().any(axis=1)]

         date  year month day  Price  Vol
2  2021-12-03  2021    12   3  71.20  NaN
6  2019-11-15  2019    11  15  63.21  NaN
9  2021-12-31  2021    12  31  75.10  NaN

In [30]:
#summary statistics
df.describe( )

            Price         Vol
count   10.000000    7.000000
mean    69.680000  387.142857
std     21.625842  124.326758
min     29.380000  200.000000
25%     64.782500  330.000000
50%     70.660000  380.000000
75%     73.652500  435.000000
max    117.250000  600.000000

In [32]:
df.describe(include="all")

              date    year  month   day       Price         Vol
count           10    10.0   10.0  10.0   10.000000    7.000000
unique          10     4.0    5.0   9.0         NaN         NaN
top     2021-12-01  2021.0   12.0   1.0         NaN         NaN
freq             1     7.0    6.0   2.0         NaN         NaN
mean           NaN     NaN    NaN   NaN   69.680000  387.142857
std            NaN     NaN    NaN   NaN   21.625842  124.326758
min            NaN     NaN    NaN   NaN   29.380000  200.000000
25%            NaN     NaN    NaN   NaN   64.782500  330.000000
50%            NaN     NaN    NaN   NaN   70.660000  380.000000
75%            NaN     NaN    NaN   NaN   73.652500  435.000000
max            NaN     NaN    NaN   NaN  117.250000  600.000000

In [33]:
df.loc[df.year==2021 & (df.month==12),:]

Empty DataFrame
Columns: [date, year, month, day, Price, Vol]
Index: []